services:
  - type: web
    name: qusis-demo-day
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: qusis-mongodb
          property: connectionString
    staticPublishPath: ./dist